### ISSUE TITLE
avoid panic if output terminates due to a downstream pipe

### ISSUE THREAD

**Issue by roycewilliams** [hops/pack2#17] opened 2020-06-27 20:30 UTC
It would be clean to support an expected end of output due to a downstream pipe:
```
$ tail -n 100000 potfile | cut -d: -f2- | pack2 unhex | head
[redacted]
[redacted]
[redacted]
[redacted]
[redacted]
[redacted]
[redacted]
[redacted]
[redacted]
[redacted]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/unhex.rs:15:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by hops** [comment] 2020-09-19 10:42
As of 9ba3fbe all errors are reported except if it's due to a broken pipe which are silently dropped.
I'll leave this issue open until someone was able to test it on Windows.

**Comment by hops** [comment] 2020-09-19 20:12
Confirmed to be working on Windows as well, therefore I'm closing this.

**Closed by hops** 2020-09-19 20:12 UTC

**Comment by roycewilliams** [comment] 2020-09-20 00:04
Awesome, thanks!
